name: konek_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  get: ^4.6.6
  google_sign_in: ^6.2.1
  flutter_easyloading: ^3.0.5
  cloud_firestore: ^4.15.5
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
  cookie_jar: ^4.0.8
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.1
  shared_preferences: ^2.2.2
  package_info: ^2.0.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.19.0
  uuid: ^4.3.3
  dropdown_button2: ^2.3.9
  firebase_messaging: ^14.7.17
  firebase_core_platform_interface: ^5.0.0
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
